# Generated by Django 4.1.1 on 2022-10-03 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='apellido',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='estudiante',
            name='nombre',
            field=models.CharField(default=2, max_length=30),
            preserve_default=False,
        ),
    ]
